-- in query (navicat Aplication) (create table function)
CREATE TABLE MAHASISWA (
    THANG YEAR,
    NIM CHAR(10) PRIMARY KEY,
    NAMA VARCHAR(50),
    ALAMAT VARCHAR(100),
    TGL DATE
);

CREATE TABLE MATKULIAH (
    KODE CHAR(5) PRIMARY KEY,
    MATAKULIAH VARCHAR(50),
    SKS INT
);

CREATE TABLE DOSEN (
    NIP CHAR(10) PRIMARY KEY,
    NAMA VARCHAR(50)
);

CREATE TABLE KELAS (
    IDKELAS INT PRIMARY KEY,
    KODE CHAR(5),
    NIP CHAR(10),
    FOREIGN KEY (KODE) REFERENCES MATKULIAH(KODE),
    FOREIGN KEY (NIP) REFERENCES DOSEN(NIP)
);

CREATE TABLE KRS (
    NIM CHAR(10),
    IDKELAS INT,
    NILAI CHAR(2),
    PRIMARY KEY (NIM, IDKELAS),
    FOREIGN KEY (NIM) REFERENCES MAHASISWA(NIM),
    FOREIGN KEY (IDKELAS) REFERENCES KELAS(IDKELAS)
);

INSERT INTO MAHASISWA (THANG, NIM, NAMA, ALAMAT, TGL) 
VALUES (2023, 'A112315194', 'Restu Ardiansyah', 'Jl. Brebes No.10', '2005-05-20');

INSERT INTO MATKULIAH (KODE, MATAKULIAH, SKS) 
VALUES ('MK001', 'Basis Data', 3);

INSERT INTO DOSEN (NIP, NAMA) 
VALUES ('D12345', 'Selamet Sudaryanto');

INSERT INTO KELAS (IDKELAS, KODE, NIP) 
VALUES (1, 'MK001', 'D12345');

INSERT INTO KRS (NIM, IDKELAS, NILAI) 
VALUES ('A112315194', 1, 'A');



