-- in query (navicat Application) (insert table function)

SELECT 
    MAHASISWA.NIM, 
    MAHASISWA.NAMA AS Nama_Mahasiswa, 
    MATKULIAH.MATAKULIAH, 
    DOSEN.NAMA AS Nama_Dosen
FROM 
    KELAS
LEFT JOIN MATKULIAH ON KELAS.KODE = MATKULIAH.KODE
LEFT JOIN DOSEN ON KELAS.NIP = DOSEN.NIP
LEFT JOIN KRS ON KELAS.IDKELAS = KRS.IDKELAS
LEFT JOIN MAHASISWA ON KRS.NIM = MAHASISWA.NIM;
