-- in Query (navicat Application) (left atble function)
SELECT 
    MAHASISWA.NIM, 
    MAHASISWA.NAMA AS Nama_Mahasiswa, 
    MAHASISWA.ALAMAT, 
    MATKULIAH.MATAKULIAH, 
    MATKULIAH.SKS, 
    DOSEN.NAMA AS Nama_Dosen, 
    KRS.NILAI
FROM 
    KRS
INNER JOIN MAHASISWA ON KRS.NIM = MAHASISWA.NIM
INNER JOIN KELAS ON KRS.IDKELAS = KELAS.IDKELAS
INNER JOIN MATKULIAH ON KELAS.KODE = MATKULIAH.KODE
INNER JOIN DOSEN ON KELAS.NIP = DOSEN.NIP;
